HiddenMeet/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using HiddenMeet.Application.Services;
using HiddenMeet.Models;
using Microsoft.AspNet.Identity;

namespace HiddenMeet.Controllers
{
    [Authorize]
    public class IndexController : BaseController
    {
        private readonly IUserService _userService;

        public IndexController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllUsers()
        {
            var users = _userService.GetAllUsers(User.Identity.GetUserId());

            var userVm = Mapper.Map<List<UserViewModel>>(users);

            return Json(userVm, JsonRequestBehavior.AllowGet);
        }
    }
}

HiddenMeet/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HiddenMeet.Infrastructure;
using Microsoft.AspNet.Identity;

namespace HiddenMeet.Controllers
{
    public class ProfileController : BaseController
    {
        private readonly UserPictureService _userPictureService;
        
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }

        public ProfileController()
        {
            _userPictureService = new UserPictureService();

        }

        [HttpGet]
        public new ActionResult Profile()
        {
            return View();
        }

        public JsonResult UpdatePictureProfile(int idUserPicture)
        {
            _userPictureService.UpdateUserPicture(idUserPicture, User.Identity.GetUserId());

            UpdateUser();

            return Json(null);
        }
    }
}

HiddenMeet/Views/Index/Index.cshtml
@model HiddenMeet.Models.UserViewModel

@{
    Layout = "~/Views/Shared/Template/_Layout.cshtml";
    ViewBag.Title = "Buscar Amigos";

    <script type="text/javascript">
        var Urls = {
            GetAllFriends: '@Url.Action("GetAllUsers", "Index")'
        };
    </script>
}
@section scripts
{
    <script src="~/Scripts/Index/Index.js"></script>
}
<div class="row" id="container-friends" data-bind="foreach: listUser">
    <div class="col-md-4">
        <div class="feed-box text-center">
            <section class="panel">
                <div class="panel-body">
                    <div class="corner-ribon black-ribon">
                    </div>
                    <a href="#">
                        <img data-bind="attr: { src: 'Images/'+ ImageProfile() }" alt="Foto perfil">
                        <h4 data-bind="text: Name"></h4>
                    </a>
                    <hr />
                    <p data-bind="text: Estatus"></p>
                </div>
            </section>
        </div>
    </div>
</div>